

CREATE TABLE FUNCIONARIO ( 
      idFunc         int NOT NULL, 
      salario              double NOT NULL, 
      nome                 varchar(40) NOT NULL,
      idGerente		int NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE FUNCIONARIO 
      ADD PRIMARY KEY ( idFunc) ;
ALTER TABLE FUNCIONARIO ADD FOREIGN KEY (idGerente) REFERENCES FUNCIONARIO  (idFunc) ;

CREATE TABLE TELEFONE_FUNC(
	idFunc		int NOT NULL,
	telefone	varchar(8)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE TELEFONE_FUNC ADD FOREIGN KEY (idFunc) REFERENCES FUNCIONARIO (idFunc);
ALTER TABLE TELEFONE_FUNC ADD PRIMARY KEY (idFunc, telefone);



CREATE TABLE VENDEDOR ( 
      idVend         int NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE VENDEDOR ADD FOREIGN KEY (idVend) REFERENCES FUNCIONARIO  (idFunc) ;

CREATE TABLE COZINHEIRO ( 
      idCoz         int NOT NULL,
      especialidade varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE COZINHEIRO ADD FOREIGN KEY (idCoz) REFERENCES FUNCIONARIO  (idFunc) ;

CREATE TABLE PEDIDO ( 
    idPedido		int NOT NULL,
    nomeCliente		varchar(50) NOT NULL,
    dataPedido			datetime NOT NULL,
    idVend				int NOT NULL
    
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
 ALTER TABLE PEDIDO 
      ADD PRIMARY KEY (idPedido) ;
     
ALTER TABLE PEDIDO ADD FOREIGN KEY (idVend) REFERENCES VENDEDOR  (idVend) ;
 

CREATE TABLE LANCHE(
	idLanche 	int NOT NULL,
	nome 		varchar(50) NOT NULL,
	valor 		double NOT NULL,
	descricao	varchar(300) null,
	categoria 	varchar(50) NOT NULL
	
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE LANCHE ADD PRIMARY KEY (idLanche);

CREATE TABLE ITEM(
	idItem		int NOT NULL,
	quantidade 	int NOT NULL,
	idCoz		int NOT NULL,
	idLanche	int NOT NULL,
	idPedido	int null

) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE ITEM ADD PRIMARY KEY (idItem);
ALTER TABLE ITEM ADD FOREIGN KEY (idCoz) REFERENCES COZINHEIRO (idCoz);
ALTER TABLE ITEM ADD FOREIGN KEY (idLanche) REFERENCES LANCHE (idLanche);
ALTER TABLE ITEM ADD FOREIGN KEY (idPedido) REFERENCES PEDIDO (idPedido);


CREATE TABLE INGREDIENTE(
	idIng		int NOT NULL,
	nome		varchar(50) NOT NULL,
	descricao	varchar(300) NULL,
	categoria 	varchar(50) NOT NULL,
	qtdDisponivel	int NOT NULL



)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE INGREDIENTE ADD PRIMARY KEY(idIng);

CREATE TABLE LANCHE_INGREDIENTE(
	idIng		int NOT NULL,
	idLanche	int NOT NULL,
	quantidade	int NOT NULL
)ENGINE = InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE LANCHE_INGREDIENTE ADD FOREIGN KEY (idIng) REFERENCES INGREDIENTE(idIng);
ALTER TABLE LANCHE_INGREDIENTE ADD FOREIGN KEY (idLanche) REFERENCES LANCHE (idLanche);
ALTER TABLE LANCHE_INGREDIENTE ADD PRIMARY KEY (idIng, idLanche);


CREATE TABLE FORNECEDOR (
	idForn 		int NOT NULL,
	nome		varchar(50) NOT NULL
	

)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE FORNECEDOR ADD PRIMARY KEY(idForn);

CREATE TABLE TELEFONE_FORN(
	idForn		int NOT NULL,
	telefone	varchar(8)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE TELEFONE_FORN ADD FOREIGN KEY (idForn) REFERENCES FORNECEDOR (idForn);
ALTER TABLE TELEFONE_FORN ADD PRIMARY KEY (idForn, telefone);

CREATE TABLE FORNECEDOR_INGREDIENTE(
	idForn		int NOT NULL,
	idIng		int NOT NULL,
	quantidade	int,
	valor		double

) ENGINE = InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE FORNECEDOR_INGREDIENTE ADD FOREIGN KEY (idForn) REFERENCES FORNECEDOR (idForn);
ALTER TABLE FORNECEDOR_INGREDIENTE ADD FOREIGN KEY (idIng) REFERENCES INGREDIENTE (idIng);
ALTER TABLE FORNECEDOR_INGREDIENTE ADD PRIMARY KEY (idForn, idIng);













